services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: aviation-api
    volumes:
      - ./:/data:ro  # Mount the standing data directory as read-only
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - aviation-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: aviation-nginx
    ports:
      - "30000:80"  # NodePort mapping - external:internal
    depends_on:
      api:
        condition: service_healthy
    networks:
      - aviation-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  aviation-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16